// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['category']['service']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['category']['service']['Delete'](arg1);
}

export function FindAll() {
  return window['go']['category']['service']['FindAll']();
}

export function FindByDescription(arg1) {
  return window['go']['category']['service']['FindByDescription'](arg1);
}

export function FindByID(arg1) {
  return window['go']['category']['service']['FindByID'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['category']['service']['Update'](arg1, arg2);
}
