// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Create(arg1:types.CategoryInput):Promise<types.Category>;

export function Delete(arg1:number):Promise<void>;

export function FindAll():Promise<Array<types.Category>>;

export function FindByDescription(arg1:string):Promise<types.Category>;

export function FindByID(arg1:number):Promise<types.Category>;

export function Update(arg1:number,arg2:types.CategoryInput):Promise<types.Category>;
