// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['expense']['service']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['expense']['service']['Delete'](arg1);
}

export function FindAll() {
  return window['go']['expense']['service']['FindAll']();
}

export function FindAllByProfileID(arg1) {
  return window['go']['expense']['service']['FindAllByProfileID'](arg1);
}

export function FindByID(arg1) {
  return window['go']['expense']['service']['FindByID'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['expense']['service']['Update'](arg1, arg2);
}
