// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {pagination} from '../models';

export function Create(arg1:types.ExpenseInput):Promise<types.Expense>;

export function Delete(arg1:number):Promise<void>;

export function FindAll():Promise<Array<types.ExpenseOutput>>;

export function FindAllByProfileID(arg1:number,arg2:pagination.Pagination):Promise<pagination.GenericPaginatedResult>;

export function FindByID(arg1:number):Promise<types.ExpenseToUpdate>;

export function Update(arg1:number,arg2:types.ExpenseUpdate):Promise<types.Expense>;
