// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Create(arg1:types.ProfileInput):Promise<types.Profile>;

export function Delete(arg1:number):Promise<void>;

export function FindAll():Promise<Array<types.Profile>>;

export function FindByID(arg1:number):Promise<types.Profile>;

export function Update(arg1:number,arg2:types.ProfileInput):Promise<types.Profile>;
