name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  build-macos:
    environment: 
        name: release
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        xcode-select --install

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Wails CLI
      run: |
        go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build for macOS/amd64
      run: |
        wails build -platform darwin/amd64
        mv ./build/bin/fintrack ./build/bin/Fintrack_MacOS_Amd64

    - name: Upload macOS arm64 binary
      uses: actions/upload-artifact@v2
      with:
        name: Fintrack_MacOS_Arm64
        path: ./build/bin/Fintrack_MacOS_Arm64

    - name: Upload macOS amd64 binary
      uses: actions/upload-artifact@v2
      with:
        name: Fintrack_MacOS_Amd64
        path: ./build/bin/Fintrack_MacOS_Amd64

  build-windows-and-linux:
    environment: 
        name: release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install Wails CLI
      run: |
        go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Build for Windows/amd64
      run: |
        wails build -platform windows/amd64
        mv ./build/bin/fintrack.exe ./build/bin/Fintrack_Windows_Amd64.exe

    - name: Build for Linux/amd64
      run: |
        wails build -platform linux/amd64
        mv ./build/bin/fintrack ./build/bin/Fintrack_Linux_Amd64

  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-macos
      - build-windows-and-linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download macOS arm64 binary
      uses: actions/download-artifact@v2
      with:
        name: Fintrack_MacOS_Arm64

    - name: Download macOS amd64 binary
      uses: actions/download-artifact@v2
      with:
        name: Fintrack_MacOS_Amd64

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./Fintrack_MacOS_Amd64
          ./build/bin/Fintrack_Windows_Amd64.exe
          ./build/bin/Fintrack_Linux_Amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}